name: init-test
on:
    push:
        branches:
            - main
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Hellow
              run: echo "hellow"
    run-go:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.22
            - name: Navigate to go-test
              run: cd go-test
            - name: Build
              run: go build
            - name: execute
              run: wisnukm41/hellow
